version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      all:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
