version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    ignore:
      # All dependencies
      - dependency-name: "*"
        # ignore all major updates
        update-types: [ "version-update:semver-major" ]
