name: Production Deploy

on:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install --frozen-lockfile

      - name: Run the tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy to Production
        run: |
          echo "Deploying to Production..."
          curl -X POST -d "deploy=true" https://mkaranfi.github.io/sandbox/
