name: Prepare Draft Release

on:
  workflow_run:
    workflows: [ "Development Deploy", "Main Workflow" ]
    types:
      - completed

jobs:
  create-draft:
    name: Create draft
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Obtain new tag
        run: |
          CURRENT=$(git tag --sort=-version:refname | head -n1)
          NEW=$(echo ${CURRENT} | awk -F. '{print $1"."$2"."$3+1}')
          echo "RELEASE_TAG=${NEW#}" >> $GITHUB_ENV

          echo current $CURRENT
          echo new $NEW

      - name: Check if auto-deploy label is set
        id: get-workflow-data
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });

            const commitSha = run.data.head_sha;

            const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha,
            });

            const mergedPRs = prs.data.filter(pr => !!pr.merged_at);

            if (mergedPRs.length === 0) {
              core.setFailed(`No PRs found for commit ${commitSha}`);
              return;
            }

            if (mergedPRs.length > 1) {
              const msg = `commit: ${commitSha}, merged PRs: ${mergedPRs.map(pr => pr.number).join(", ")}`
              core.info(msg);
              core.setFailed("Multiple merged PRs found associated with commit, not sure what to do..");
              return;
            }

            const pr = mergedPRs[0];
            const labels = pr.labels.map(label => label.name);
            core.info(`PR labels: ${labels.join(", ")}`);

            const hasAutoDeploy = labels.includes("auto-deploy");
            core.setOutput("auto_deploy", hasAutoDeploy);

      - name: Create release
        id: create-release
        uses: actions/github-script@v7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              let release = await github.rest.repos.createRelease({
                draft: ${{ steps.get-workflow-data.outputs.auto_deploy != 'true' }},
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                target_commitish: "master",
                tag_name: process.env.RELEASE_TAG,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
