name: Prepare Draft Release

on:
  workflow_run:
    workflows: [ "Development Deploy", "Main Workflow" ]
    types:
      - completed

jobs:
  create-draft:
    name: Create draft
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Obtain new tag
        run: |
          CURRENT=$(git tag --sort=-version:refname | head -n1)
          NEW=$(echo ${CURRENT} | awk -F. '{print $1"."$2"."$3+1}')
          echo "RELEASE_TAG=${NEW#}" >> $GITHUB_ENV

          echo current $CURRENT
          echo new $NEW

      - name: Get PR labels
        id: merged-pr-labels
        uses: kiprasmel/merged-pr-labels@v0.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if auto-deploy label is set
        id: get-workflow-data
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = ${{ steps.merged-pr-labels.outputs.labels }};
            const hasAutoDeploy = labels.includes("auto-deploy");

            core.info(`PR labels: ${labels.join(", ")}`);
            core.info(`hasAutoDeploy: ${hasAutoDeploy}`);

            core.setOutput("auto_deploy", hasAutoDeploy);

      - name: Create release
        id: create-release
        uses: actions/github-script@v7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              const draft = ${{ steps.get-workflow-data.outputs.auto_deploy != 'true' }}

              const release = await github.rest.repos.createRelease({
                draft,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                target_commitish: "master",
                tag_name: process.env.RELEASE_TAG,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
